name: "Run pip-compile"
description: "Install pip-tools and run pip-compile on a set of requirements files."
inputs:
  requirements_files:
    description: |-
      The paths to the requirements files to compile. Files will be compiled
      in the order they are listed. To specify multiple files, use the following
      syntax:

      requirements_files: |-
        path/to/requirements1.txt
        path/to/requirements2.txt
    required: true

runs:
  using: "composite"
  steps:

      - name: Run pip-compile
        id: run-pip-compile
        uses: UW-GAC/pip-tools-actions/run-pip-compile@main
        with:
          requirements_files: ${{ inputs.requirements_files }}

      - name: Fail if there are changes to the files
        if: steps.run-pip-compile.outputs.FILES_CHANGED
        run: exit 1
        shell: bash
