name: "Update requirements files"
description: "Run pip-compile and open a pull request to update the requirements files."
inputs:
  requirements_files:
    description: |-
      The paths to the requirements files to compile. Files will be compiled
      in the order they are listed. To specify multiple files, use the following
      syntax:

      requirements_files: |-
        path/to/requirements1.txt
        path/to/requirements2.txt
    required: true
  pr-commit-message:
    description: "The commit message to use for the pull request."
    required: false
    default: "Compile requirements files"
  pr-title:
    description: "The title to use for the pull request."
    required: false
    default: "Compile requirements files"
  pr-body:
    description: "The body to use for the pull request."
    required: false
    default: "Compile requirements files"
  pr-labels:
    description: "The labels to apply to the pull request."
    required: false
    default: "automated-pr, pip-compile"
  pr-base:
    description: "The base branch to open the pull request against."
    required: false
    default: "main"

runs:
  using: "composite"
  steps:

      - name: Run pip-compile
        uses: UW-GAC/pip-tools-actions/run-pip-compile@main
        with:
          requirements_files: ${{ inputs.requirements_files }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
            commit-message: ${{ inputs.pr-commit-message }}
            title: ${{ inputs.pr-title }}
            body: ${{ inputs.pr-body }}
            labels: ${{ inputs.pr-labels }}
            base: ${{ inputs.pr_base }}
            # Create a new branch each run.
            branch: pip-tools/update-requirements-files-${{ github.run_id }}
