name: "Update requirements files"
description: |-
  Run pip-compile and open a pull request to update the requirements files.

  Note: when using this action with on: pull_request, you should check out the head_ref.
inputs:
  requirements_files:
    description: |-
      The paths to the requirements files to compile. Files will be compiled
      in the order they are listed. To specify multiple files, use the following
      syntax:

      requirements_files: |-
        path/to/requirements1.txt
        path/to/requirements2.txt
    required: true
  pr-commit-message:
    description: "The commit message to use for the pull request."
    required: false
    default: "Compile requirements files"
  pr-title:
    description: "The title to use for the pull request."
    required: false
    default: "Update requirements files"
  pr-body:
    description: "The body to use for the pull request."
    required: false
    default: "Compile requirements files"
  pr-labels:
    description: "The labels to apply to the pull request."
    required: false
    default: "automated-pr, update-requirements-files"
  pr-branch-suffix:
    description: "A suffix to append to the branch name."
    required: true

runs:
  using: "composite"
  steps:

      - name: Run pip-compile
        id: run-pip-compile
        uses: UW-GAC/pip-tools-actions/run-pip-compile@main
        with:
          requirements_files: ${{ inputs.requirements_files }}

      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
            commit-message: ${{ inputs.pr-commit-message }}
            title: ${{ inputs.pr-title }}
            body: ${{ inputs.pr-body }}
            labels: ${{ inputs.pr-labels }}
            # Create a new branch for each pull request.
            branch: pip-tools/update-requirements-files/${{ inputs.pr-branch-suffix }}

      - name: "Fail if there are changes to requirements files"
        if: steps.run-pip-compile.outputs.FILES_CHANGED
        run: |
          echo "Changes to requirements files detected"
          echo "Please merge pull request to resolve:"
          echo "${{ steps.create-pull-request.outputs.pull-request-url }}"
          exit 1
        shell: bash
