name: "Update requirements files"
description: |-
  Run pip-compile and open a pull request to update the requirements files.

  Note: when using this action with on: pull_request, you should check out the head_ref.
inputs:
  requirements_files:
    description: |-
      The paths to the requirements files to compile. Files will be compiled
      in the order they are listed. To specify multiple files, use the following
      syntax:

      requirements_files: |-
        path/to/requirements1.txt
        path/to/requirements2.txt
    required: true
  pip-tools-version:
    description: "The version of pip-tools to install. If not specified, the most recent version will be installed."
    required: false
    default: ""
  pip-compile-args:
    description: "Additional arguments to pass to pip-compile."
    required: false
    default: ""
  pr-commit-message:
    description: "The commit message to use for the pull request."
    required: false
    default: "Compile requirements files"
  pr-title:
    description: "The title to use for the pull request."
    required: false
    default: "Update requirements files"
  pr-body:
    description: "The body to use for the pull request."
    required: false
    default: "Compile requirements files"
  pr-labels:
    description: "The labels to apply to the pull request."
    required: false
    default: "automated-pr, update-requirements-files"
  pr-branch-suffix:
    description: "A suffix to append to the branch name."
    required: true

runs:
  using: "composite"
  steps:

      - name: Symlink current action repo
        env:
          action_path: ${{ github.action_path }}
        run: |
          if [[ ! -d .github/.action_repo ]]; then ln -fs ${{ env.action_path }}/.. .github/.action_repo; fi
        shell: bash

      - name: Run pip-compile
        id: run-pip-compile
        uses: ./.github/.action_repo/run-pip-compile
        with:
          requirements_files: ${{ inputs.requirements_files }}
          pip-tools-version: ${{ inputs.pip-tools-version }}
          pip-compile-args: ${{ inputs.pip_compile_args }}

      - name: Prep output files for pull request
        id: prep-output-files
        run: |
          # Replace spaces with commas
          echo "${{ steps.run-pip-compile.outputs.OUTPUT_FILES }}"
          output_files_pr="${${{ steps.run-pip-compile.outputs.OUTPUT_FILES }}// /","}"
          echo $output_files_pr
          echo "OUTPUT_FILES_PR=${output_files_pr}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Pull Request
        if: steps.run-pip-compile.outputs.CHANGES_DETECTED == '1'
        id: create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
            commit-message: ${{ inputs.pr-commit-message }}
            title: ${{ inputs.pr-title }}
            body: ${{ inputs.pr-body }}
            labels: ${{ inputs.pr-labels }}
            # Create a new branch for each pull request.
            branch: pip-tools/update-requirements-files/${{ inputs.pr-branch-suffix }}
            add-paths: ${{ steps.prep-output-files.outputs.OUTPUT_FILES_PR }}

      - name: "Fail if there are changes to requirements files"
        if: steps.run-pip-compile.outputs.CHANGES_DETECTED == '1'
        run: |
          echo "Changes to requirements files detected"
          echo "Please merge pull request to resolve:"
          echo "${{ steps.create-pull-request.outputs.pull-request-url }}"
          exit 1
        shell: bash
