name: "Run pip-compile"
description: "Install pip-tools and run pip-compile on a set of requirements files."
inputs:
  requirements_files:
    description: |-
      The paths to the requirements files to compile. Files will be compiled
      in the order they are listed. To specify multiple files, use the following
      syntax:

      requirements_files: |-
        path/to/requirements1.txt
        path/to/requirements2.txt
    required: true

runs:
  using: "composite"
  steps:

      - name: Set up pip-tools
        uses: UW-GAC/pip-tools-actions/setup-pip-tools@main

      # For now, just run on a single file in a specific location.
      # Later, we can make this an input to the workflow.
      - name: Run pip-compile
        id: run-pip-compile
        run: |
          for i in $INPUT_REQUIREMENTS_FILES
          do
            echo "Compiling $i"
            pip-compile $i
          done
        shell: bash
        env:
          INPUT_REQUIREMENTS_FILES: ${{ inputs.requirements_files }}

      - name: Set output
        id: pip-compile-changes
        run: |
          function check() {
            if [[ -z "$(git status --porcelain $STATUS_ARGS $PATHSPEC)" ]];
            then
              echo "0"
            else
              echo "1"
            fi
          }

          echo "name=changed::$(check) >> $GITHUB_OUTPUT"
        shell: bash

      - name: List changes
        run: |
          git status
          git diff
        shell: bash

      - name: "Test printing output"
        run: |
          echo "Changed: ${{ steps.pip-compile-changes.outputs.changed }}"
        shell: bash
