name: "Run pip-compile"
description: "Install pip-tools and run pip-compile on a set of requirements files."

runs:
  using: "composite"
  steps:

      - name: Set up pip-tools
        uses: UW-GAC/pip-tools-actions/setup-pip-tools@main

      # For now, just run on a single file in a specific location.
      # Later, we can make this an input to the workflow.
      - name: Run pip-compile
        run: |
          pip-compile requirements/requirements.in
        shell: bash

      - name: List changes
        run: |
          git status
          git diff
        shell: bash
