name: "Run pip-compile"
description: "Install pip-tools and run pip-compile on a set of requirements files."
inputs:
  requirements_files:
    description: |-
      The paths to the requirements files to compile. Files will be compiled
      in the order they are listed. To specify multiple files, use the following
      syntax:

      requirements_files: |-
        path/to/requirements1.txt
        path/to/requirements2.txt
    required: true
  pip-tools-version:
    description: "The version of pip-tools to install. If not specified, the most recent version will be installed."
    required: false
    default: ""
  pip-compile-args:
    description: "Additional arguments to pass to pip-compile."
    required: false
    default: ""
outputs:
  files_changed:
    description: "A flag indicating whether the requirements files have changed."
    value: ${{ steps.pip-compile-changes.outputs.CHANGES_DETECTED }}

runs:
  using: "composite"
  steps:

      - name: Symlink current action repo
        env:
          action_path: ${{ github.action_path }}
        run: |
          if [[ ! -d .github/.action_repo ]]; then ln -fs ${{ env.action_path }}/.. .github/.action_repo; fi
        shell: bash

      - name: Set up pip-tools
        uses: ./.github/.action_repo/setup-pip-tools
        with:
          pip-tools-version: ${{ inputs.pip-tools-version }}

      # For now, just run on a single file in a specific location.
      # Later, we can make this an input to the workflow.
      - name: Run pip-compile
        id: run-pip-compile
        run: |
          for i in $INPUT_REQUIREMENTS_FILES
          do
            echo "Compiling $i"
            pip-compile $INPUT_PIP_COMPILE_ARGS $i
          done
        shell: bash
        env:
          INPUT_REQUIREMENTS_FILES: ${{ inputs.requirements_files }}
          INPUTS_PIP_COMPILE_ARGS: ${{ inputs.pip_compile_args }}

      - name: Get names of output files from pip-compile
        id: get-output-files
        run: |
          output_files=()
          for file in $INPUT_REQUIREMENTS_FILES
          do
            output_files+=("${file%.in}.txt")
          done
          echo "OUTPUT_FILES=${output_files[@]}" >> $GITHUB_OUTPUT
        shell: bash
        env:
          INPUT_REQUIREMENTS_FILES: ${{ inputs.requirements_files }}

      - name: Set output
        id: pip-compile-changes
        run: |
          function check() {
            if [[ -z "$(git status --porcelain  ${{ steps.get-output-files.outputs.OUTPUT_FILES}})" ]];
            then
              echo "0"
            else
              echo "1"
            fi
          }

          echo "CHANGES_DETECTED=$(check)" >> $GITHUB_OUTPUT
        shell: bash

      - name: List changes
        if: steps.pip-compile-changes.outputs.CHANGES_DETECTED
        run: |
          git status ${{ steps.get-output-files.outputs.OUTPUT_FILES}}
          git diff
        shell: bash
