name: "Run pip-compile"
description: "Install pip-tools and run pip-compile on a set of requirements files."
inputs:
  requirements_files:
    description: "The paths to the requirements files to compile. Files will be compiled in the order they are listed."
    required: true

runs:
  using: "composite"
  steps:

      # - name: Set up pip-tools
      #   uses: UW-GAC/pip-tools-actions/setup-pip-tools@main

      # For now, just run on a single file in a specific location.
      # Later, we can make this an input to the workflow.
      - name: Run pip-compile
        run: |
          echo $INPUT_REQUIREMENTS_FILES
          for i in $sentence
          do:
            echo $i
          done
        shell: bash
        env:
          INPUT_REQUIREMENTS_FILES: ${{ inputs.requirements_files }}

      # - name: List changes
      #   run: |
      #     git status
      #     git diff
      #   shell: bash
