name: "Check requirements files"
description: "Set up pip-tools, recompile requirements files, and fail if there are changes."
inputs:
  requirements_files:
    description: |-
      The paths to the requirements files to compile. Files will be compiled
      in the order they are listed. To specify multiple files, use the following
      syntax:

      requirements_files: |-
        path/to/requirements1.txt
        path/to/requirements2.txt
    required: true
  pip-tools-version:
    description: "The version of pip-tools to install. If not specified, the most recent version will be installed."
    required: false
    default: ""
  pip-compile-args:
    description: "Additional arguments to pass to pip-compile."
    required: false
    default: ""

runs:
  using: "composite"
  steps:

      - name: Symlink current action repo
        env:
          action_path: ${{ github.action_path }}
        run: |
          if [[!  -d .github/.action_repo ]]; then ln -fs ${{ env.action_path }}/.. .github/.action_repo; fi

      - name: Run pip-compile
        id: run-pip-compile
        uses: ./.github/.action_repo/run-pip-compile
        with:
          requirements_files: ${{ inputs.requirements_files }}
          pip-tools-version: ${{ inputs.pip-tools-version }}
          pip-compile-args: ${{ inputs.pip_compile_args }}

      - name: "Fail if there are changes to requirements files"
        if: steps.run-pip-compile.outputs.FILES_CHANGED == '1'
        run: |
          echo "Changes to requirements files detected"
          exit 1
        shell: bash
