name: "Run pip-compile"
description: "Install pip-tools and run pip-compile on a set of requirements files."
inputs:
  pip-tools-version:
    description: "The version of pip-tools to install. If not specified, the most recent version will be installed."
    required: false
    default: ""

runs:
  using: "composite"
  steps:

      - name: Get pip-tools version suffix
        id: get-pip-tools-version-suffix
        run: |
          if [[ -z "${{ inputs.pip-tools-version }}" ]];
          then
            echo "using latest version of pip-tools";
          else
            echo "PIP_TOOLS_VERSION==${{ inputs.pip-tools-version }}" >> $GITHUB_OUTPUT;
          fi
        shell: bash

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools${{ steps.get-pip-tools-version-suffix.outputs.PIP_TOOLS_VERSION }}
        shell: bash
