name: "Run pip-compile"
description: "Install pip-tools and run pip-compile on a set of requirements files."

runs:
  using: "composite"
  steps:

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
        shell: bash
